---
- hosts: centos
  become: yes
  tasks: 
    - name: install httpd
      yum: 
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        service: started
    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/


- hosts: ubuntu
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start apache2
      service:
        name: apache2
        service: started
    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/

    
    
