- hosts: centos
  become: yes
  tasks: 

    - name: install java 1.8 
      yum:
        name: java-1.8.0-openjdk.x86_64
        state: installed
        
    - name: getting jenking key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present
      tags: key

    - name: getting jenkins repo
      get_url: 
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      tags: repo

    - name: install jenkins
      yum:
        name: jenkins
        state: present
        update_cache: yes

    - name: change port number
      replace: 
        path: /etc/sysconfig/jenkins
        regexp: JENKINS_PORT=8080
        replace: JENKINS_PORT=9090

    - name: start jenkins
      service:
        name: jenkins
        state: restarted
        enabled: yes
